### ISSUE TITLE
[BUG] ServiceByName org.freedesktop.secrets runs into a timeout

### ISSUE THREAD

**Issue by IngwiePhoenix** [linuxserver/docker-mysql-workbench#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to connect to a MySQL server in the same docker-compose deployment, setting the password runs into this error:

![image](https://github.com/user-attachments/assets/e584e297-9aab-461f-a775-13d29c73c38a)

The IPC lock cap is enabled.

### Expected Behavior

I expected to save a password.

### Steps To Reproduce

1. Deploy
2. Attempt to connect
3. Observe the error

`compose.yml`:
```yaml
services:
  wk:
    image: lscr.io/linuxserver/mysql-workbench:latest
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - START_DOCKER=true
      - LC_ALL=de_DE.UTF-8
      - NO_DECOR=true
    volumes:
      - "./workbench:/config"
      #- "/var/run/docker.sock:/var/run/docker.sock"
      - "/dev/dri:/dev/dri"
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
  mysql:
    image: mysql:8.0-debian
    #command: mysqld --skip-ssl --sha256-password-auto-generate-rsa-keys=OFF --caching-sha2-password-auto-generate-rsa-keys=OFF
    volumes:
      - "mysql-data:/var/lib/mysql"
    environment:
      - "TZ=Europe/Berlin"
      - "MYSQL_ROOT_PASSWORD=thisisnotsafeandidontcare"
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mysql-data:
```

Reason for `mysql-data` is an annoying "bug" whereby permissions go all out of whack when mounting a local Windows folder through Podman, which runs in WSL. It's all over the place...

### Environment

```markdown
- OS: Windows 10
- How docker service was installed: Podman, docker-compose CLI. Deployment is above.
```

### CPU architecture

x86-64

### Docker creation

```bash
See above.
```

### Container logs

```bash
None to note, the error is not logged.
```
